// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiC9hospFlRc2V3OWoLHHaz7E7NAGu4kE',
    appId: '1:486214455905:web:a304694e61d519fc83d020',
    messagingSenderId: '486214455905',
    projectId: 'kassku-money',
    authDomain: 'kassku-money.firebaseapp.com',
    storageBucket: 'kassku-money.appspot.com',
    measurementId: 'G-RHVK9PFYPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk_rk1xfb0a5ROZiniEMaRDLV4K2uY6GA',
    appId: '1:486214455905:android:8fd13422f2685cef83d020',
    messagingSenderId: '486214455905',
    projectId: 'kassku-money',
    storageBucket: 'kassku-money.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9K10jtcgyxHDHLNQ6exMLEzNF0GB1BA',
    appId: '1:486214455905:ios:ff54e2e41d4dac0c83d020',
    messagingSenderId: '486214455905',
    projectId: 'kassku-money',
    storageBucket: 'kassku-money.appspot.com',
    iosClientId: '486214455905-19bhnhvc9e64akjup47q48ruv9f51igf.apps.googleusercontent.com',
    iosBundleId: 'id.cloed.kassku.ios',
  );
}
